import { Poppins } from "next/font/google";
import "./globals.css";
import SplashScreen from "./SplashScreen";
import Provider from "./Provider";
import { ColorModeScript } from "@chakra-ui/react";
import theme from "./libs/theme";

const font = Poppins({ subsets: ["latin"], weight: "300" });

export const metadata = {
  title: "Aldiipratama | Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/img/favicon.ico",
    apple: "/assets/img/apple-touch-icon.png",
    other: [
      {
        url: "/assets/img/favicon-16x16.png",
        rel: "icon",
      },
      {
        rel: "icon",
        url: "/assets/img/favicon-32x32.png",
      },
      {
        rel: "icon",
        url: "/assets/img/android-chrome-192x192.png",
      },
      {
        rel: "icon",
        url: "/assets/img/android-chrome-512x512.png",
      },
    ],
  },
  manifest: "assets/img/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <SplashScreen />
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
